export const ShoppingCartActionTypes = {
    TOGGLE_SHOPPING_CART_DROPDOWN_HIDDEN: 'TOGGLE_SHOPPING_CART_DROPDOWN_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_SHOPPING_ITEM: 'REMOVE_SHOPPING_ITEM',
    DELETE_ITEM_FROM_SHOPPING_CART: 'DELETE_ITEM_FROM_SHOPPING_CART',
    CLEAR_SHOPPING_CART: 'CLEAR_SHOPPING_CART',
    SET_CART_FROM_FIREBASE: 'SET_CART_FROM_FIREBASE',
    UPDATE_CART_IN_FIREBASE: 'UPDATE_CART_IN_FIREBASE'
};